name: Build t3-gem-nextcloud

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
        
      - name: Setup LFS
        run: |
          sudo apt-get install git-lfs -y
          git lfs install --local
          git lfs pull

      - name: Install taskfile for build project
        run: |
            mkdir "${GITHUB_WORKSPACE}/bin"
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b "${GITHUB_WORKSPACE}/bin"

      - name: Install fakeroot
        run: sudo apt install -y fakeroot 
      
      - name: Build project
        run: |
            "${GITHUB_WORKSPACE}/bin/task" release
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: t3-gem-nextcloud
          path: ${{ github.workspace }}/release/*
